apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: remote-print
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: nginx
          image: remote-print-frontend:local
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 80 } ]
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: remote-print
spec:
  selector: { app: frontend }
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
